version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ysolarh/backend:latest
    container_name: backend
    env_file:
      - .env
    environment:
      - DB_HOST=${MYSQL_HOST}
    volumes:
      - ./app:/backend/app
      - ./mysite:/backend/mysite
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    container_name: db
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER = ${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Asia/Seoul
    ports:
      - "33306:3306"


