version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env-be/.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "54321:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    volumes:
      - ./apps:/backend/apps
      - ./config:/backend/config
      - ./tools:/backend/tools
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

