on:
  push:
    branches: [ develop ]

name: CI

jobs:
  ci:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:16.2-alpine3.19
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }} 
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout the codes
        uses: actions/checkout@v3

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Install Poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run:
          poetry install
      
      - name: Add profile credentials
        run: | 
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_region ${{ secrets.AWS_REGION }} --profile ${{ secrets.AWS_PROFILE }}
          
      - name: Switch to prod
        run: |
          ln -sf prod.py config/settings/settings.py

      - name: Run black
        run: |
          poetry run black . --check

      - name: Run isort
        run: |
          poetry run isort . --check --diff

      - name: Run Mypy
        run: |
          poetry run mypy .
      
      - name: Run makemigrations
        run: |
          poetry run python manage.py makemigrations category chat product user

      - name: Run migrate
        run: |
          poetry run python manage.py migrate

      - name: Run test
        run: |
          poetry run python manage.py test
