name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

      - name: Build the Docker image
        uses: actions/checkout@v4
        run: |
          docker build -t $DOCKER_USER/$DOCKER_IMAGE:latest .
          
      - name: Docker push
        run: |
          docker push $DOCKER_USER/$IMAGE:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
      BE_PORT: ${{ secrets.BE_PORT }}
      BE_CONTAINER: ${{ secrets.BE_CONTAINER }}
      BE_NETWORK: ${{ secrets.BE_NETWORK }}
      BE_VOLUME: ${{ secrets.BE_VOLUME
    steps:
      - name: Deploy Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          port: $PORT
          script: |
            docker pull $DOCKER_USER/$DOCKER_IMAGE:latest
            docker rm -f backend
            docker run -d -p $BE_PORT:$BE_PORT --name $BE_CONTAINER --network $BE_NETWORK -v $BE_VOLUME $DOCKER_USER/$DOCKER_IMAGE:latest

